-- WEB 계정 생성
CREATE USER BEBENO IDENTIFIED BY BEBENO;
GRANT RESOURCE, CONNECT TO BEBENO;

------------------------------------------------
--------------- BBN_STORE 관련 테이블 ---------------
------------------------------------------------
DROP TABLE BBN_STORE;
DROP SEQUENCE SEQ_STORE_NO;

CREATE TABLE BBN_STORE (
    STORE_NO NUMBER PRIMARY KEY,
    STORE_WRITERNO NUMBER,
    STORE_KORNAME VARCHAR2(100),
    STORE_ENGNAME VARCHAR2(100),
    STORE_ADDRESS VARCHAR2(100),
    STORE_PHONE VARCHAR2(20),
    STORE_TIME VARCHAR2(100),
    STORE_TYPE VARCHAR2(20) CHECK(STORE_TYPE IN('와인샵', '레스토랑')),
    STORE_IMGURL VARCHAR2(100),
    STORE_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STORE_STATUS IN('Y', 'N')),
    STORE_CONTENT VARCHAR2(2000), 
	ORIGINAL_FILENAME VARCHAR2(100), 
	RENAMED_FILENAME VARCHAR2(100), 
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN BBN_STORE.STORE_NO IS '상점고유번호';
COMMENT ON COLUMN BBN_STORE.STORE_WRITERNO IS '작성자고유번호';
COMMENT ON COLUMN BBN_STORE.STORE_KORNAME IS '한글상호';
COMMENT ON COLUMN BBN_STORE.STORE_ENGNAME IS '영문상호';
COMMENT ON COLUMN BBN_STORE.STORE_ADDRESS IS '주소';
COMMENT ON COLUMN BBN_STORE.STORE_PHONE IS '연락처';
COMMENT ON COLUMN BBN_STORE.STORE_TIME IS '운영시간';
COMMENT ON COLUMN BBN_STORE.STORE_TYPE IS '업종';
COMMENT ON COLUMN BBN_STORE.STORE_IMGURL IS '이미지주소';
COMMENT ON COLUMN BBN_STORE.STORE_STATUS IS '상태값';
COMMENT ON COLUMN BBN_STORE.STORE_CONTENT IS '내용';
COMMENT ON COLUMN BBN_STORE.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN BBN_STORE.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN BBN_STORE.ENROLL_DATE IS '등록일';
COMMENT ON COLUMN BBN_STORE.MODIFY_DATE IS '수정일';

CREATE SEQUENCE SEQ_STORE_NO;

INSERT INTO BBN_STORE VALUES(SEQ_STORE_NO.NEXTVAL, 1, '바틀샵 송도캠퍼스타운점', '', '인천 연수구 송도과학로27번길 55 301동 B-124호',  '032-812-8003', '11:00 - 23:00', '와인샵', 'https://ifh.cc/g/sOXBoB.jpg', 'Y', '', '', '',SYSDATE, SYSDATE);
INSERT INTO BBN_STORE VALUES(SEQ_STORE_NO.NEXTVAL, 1, '비스트로네모', '', '인천 연수구 송도과학로27번길 55 c동 118호',  '0507-1394-3123', '17:00 - 00:00', '레스토랑', 'https://ifh.cc/g/p743aO.jpg', 'Y', '', '', '', SYSDATE, SYSDATE);

COMMIT;

