-- <bebeno table>
-- BEBENO_USER 테이블 생성
CREATE TABLE BEBENO_USER (
	USER_ID VARCHAR2(20) NOT NULL,
	USER_PASSWORD VARCHAR2(100) NOT NULL,
	USER_NAME VARCHAR2(20) NOT NULL,
	USER_EMAIL VARCHAR2(50) NOT NULL,
	USER_BIRTH VARCHAR2(20) NOT NULL,
  	ORIGINAL_PROFILENAME VARCHAR2(100), 
	RENAMED_PROFILENAME VARCHAR2(100),
	USER_PHONE VARCHAR2(20) NOT NULL,
	USER_ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
	USER_ENROLLDATE	DATE DEFAULT SYSDATE
);

-- <CREATE COMMENT>
-- BEBENO_USER 테이블 COMMENT 추가
COMMENT ON COLUMN BEBENO_USER.USER_ID IS '아이디';
COMMENT ON COLUMN BEBENO_USER.USER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN BEBENO_USER.USER_NAME IS '이름';
COMMENT ON COLUMN BEBENO_USER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN BEBENO_USER.ORIGINAL_PROFILENAME IS '원본프로필사진';
COMMENT ON COLUMN BEBENO_USER.RENAMED_PROFILENAME IS '수정프로필사진';
COMMENT ON COLUMN BEBENO_USER.USER_PHONE IS '전화번호';
COMMENT ON COLUMN BEBENO_USER.USER_ROLE IS '유저권한';
COMMENT ON COLUMN BEBENO_USER.USER_BIRTH IS '생일';

---------------------------------------------------
-- 관리자 페이지 
---------------------------------------------------

-- ADMIN 테이블 생성
CREATE TABLE ADMIN (
	ADMIN_NO NUMBER NOT NULL,
	ADMIN_ID VARCHAR2(20)NOT NULL
);

-- ADMIN 테이블 COMMENT 추가
COMMENT ON COLUMN ADMIN.ADMIN_NO IS '관리자번호';
COMMENT ON COLUMN ADMIN.ADMIN_ID IS '아이디';

-------------------------------------------------
-------------------------------------------------
CREATE TABLE WINEBOARD (	
    NO NUMBER,
    WRITER_NO NUMBER, 
	TITLE VARCHAR2(50), 
	CONTENT VARCHAR2(2000), 
	ORIGINAL_FILENAME VARCHAR2(100), 
	RENAMED_FILENAME VARCHAR2(100), 
	READCOUNT NUMBER DEFAULT 0, 
    CREATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_WINEBOARD_WRITER FOREIGN KEY(WRITER_NO) REFERENCES ADMIN(ADMIN_NO) ON DELETE SET NULL,
    CONSTRAINT PK_WINEBOARD_NO PRIMARY KEY(NO)
);

alter table wineboard add primary key(no);

COMMENT ON COLUMN WINEBOARD.NO IS '게시글번호';
COMMENT ON COLUMN WINEBOARD.WRITER_NO IS '게시글작성자';
COMMENT ON COLUMN WINEBOARD.TITLE IS '게시글제목';
COMMENT ON COLUMN WINEBOARD.CONTENT IS '게시글내용';
COMMENT ON COLUMN WINEBOARD.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN WINEBOARD.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN WINEBOARD.READCOUNT IS '조회수';
COMMENT ON COLUMN WINEBOARD.CREATE_DATE IS '게시글올린날짜';

CREATE SEQUENCE SEQ_WINEBOARD_NO;

alter table wineboard add primary key(admin_no);


DROP TABLE WINEBOARD;