-- 제 파트만 추려놓은 Script파일 입니다.


-- WEB 계정 생성
-- CREATE USER BEBENO IDENTIFIED BY BEBENO;
-- GRANT RESOURCE, CONNECT TO BEBENO;


-- 순차적 테이블 삭제 리스트
-- ================================================
Drop table bbn_order;
DROP SEQUENCE SEQ_ORDER_ID;

-- BEBENO_WINEBOARD, MEMBER 테이블을 참조하므로 선행삭제 필요
DROP TABLE CART;
DROP SEQUENCE SEQ_CART_NO;

-- ================================================

-- MEMBER, WAGLE_BOARD 테이블을 참조하므로 선행삭제 필요
DROP TABLE SCRAP;
DROP SEQUENCE SEQ_SCRAP_NO;

-- ================================================

-- MEMBER, WAGLE_BOARD 테이블을 참조하므로 선행삭제 필요
DROP TABLE WAGLE_BOARD_REPLY;
DROP SEQUENCE SEQ_WAGLE_REPLY_NO;

-- WAGLE_BOARD 테이블을 참조하므로 선행삭제 필요
DROP TABLE WAGLE_FILE;
DROP SEQUENCE SEQ_W_FILE_NO;

-- BBN_STORE, BEBENO_WINEBOARD, MEMBER테이블을 참조하므로 선행삭제 필요
DROP TABLE WAGLE_BOARD;
DROP SEQUENCE SEQ_WAGLE_BOARD_NO;

-- ================================================

-- BBN_STORE를 참조하고 있기 때문에 먼저 삭제해야 함
DROP TABLE STORE_FILE;
DROP SEQUENCE SEQ_S_FILE_NO;

DROP TABLE BBN_STORE;
DROP SEQUENCE SEQ_STORE_NO;

-- ================================================

DROP TABLE MEMBER;
DROP SEQUENCE SEQ_UNO;

-- ================================================

DROP TABLE BEBENO_WINEBOARD;
DROP SEQUENCE SEQ_WINE_NO;

-- ================================================

------------------------------------------------
-------------- BBN_STORE 관련 테이블 ------------
------------------------------------------------

CREATE TABLE BBN_STORE (
    STORE_NO NUMBER PRIMARY KEY,
    STORE_WRITERNO NUMBER,
    STORE_KORNAME VARCHAR2(100),
    STORE_ENGNAME VARCHAR2(100),
    STORE_ZIPCODE NUMBER,
    STORE_ADDRESS1 VARCHAR2(100),
    STORE_ADDRESS2 VARCHAR2(100),
    STORE_PHONE VARCHAR2(20),
    STORE_TIME VARCHAR2(100),
    STORE_TYPE VARCHAR2(20) CHECK(STORE_TYPE IN('와인샵', '레스토랑')),
    STORE_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STORE_STATUS IN('Y', 'N')),
    STORE_CONTENT VARCHAR2(2000), 
    STORE_CONTENT2 VARCHAR2(2000),
	ORIGINAL_FILENAME VARCHAR2(100), 
	RENAMED_FILENAME VARCHAR2(100), 
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN BBN_STORE.STORE_NO IS '상점고유번호';
COMMENT ON COLUMN BBN_STORE.STORE_WRITERNO IS '작성자고유번호';
COMMENT ON COLUMN BBN_STORE.STORE_KORNAME IS '한글상호';
COMMENT ON COLUMN BBN_STORE.STORE_ENGNAME IS '영문상호';
COMMENT ON COLUMN BBN_STORE.STORE_ZIPCODE IS '우편번호';
COMMENT ON COLUMN BBN_STORE.STORE_ADDRESS1 IS '주소1';
COMMENT ON COLUMN BBN_STORE.STORE_ADDRESS2 IS '주소2';
COMMENT ON COLUMN BBN_STORE.STORE_PHONE IS '연락처';
COMMENT ON COLUMN BBN_STORE.STORE_TIME IS '운영시간';
COMMENT ON COLUMN BBN_STORE.STORE_TYPE IS '업종';
COMMENT ON COLUMN BBN_STORE.STORE_STATUS IS '상태값';
COMMENT ON COLUMN BBN_STORE.STORE_CONTENT IS '내용';
COMMENT ON COLUMN BBN_STORE.STORE_CONTENT2 IS '내용2';
COMMENT ON COLUMN BBN_STORE.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN BBN_STORE.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN BBN_STORE.ENROLL_DATE IS '등록일';
COMMENT ON COLUMN BBN_STORE.MODIFY_DATE IS '수정일';

CREATE SEQUENCE SEQ_STORE_NO;


------------------------------------------------
-------------- STORE_FILE 관련 테이블 ------------
------------------------------------------------
CREATE TABLE STORE_FILE (
    S_FILE_NO NUMBER PRIMARY KEY,
    STORE_NO NUMBER,
    ORIGINAL_FILENAME VARCHAR2(100),
	RENAMED_FILENAME VARCHAR2(100),
    FOREIGN KEY (STORE_NO) REFERENCES BBN_STORE (STORE_NO)
);

CREATE SEQUENCE SEQ_S_FILE_NO;

COMMENT ON COLUMN STORE_FILE.S_FILE_NO IS '파일고유번호';
COMMENT ON COLUMN STORE_FILE.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN STORE_FILE.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN STORE_FILE.STORE_NO IS '상점고유번호';

------------------------------------------------
-------------- STORE_WINES 관련 테이블 ------------
------------------------------------------------
CREATE TABLE STORE_WINES (
    NO NUMBER PRIMARY KEY,
    STORE_NO NUMBER,
    WINE_NAME VARCHAR2(100), 
    WINE_ENG VARCHAR2(100),
    ORIGINAL_FILENAME VARCHAR2(100),
	RENAMED_FILENAME VARCHAR2(100),
    FOREIGN KEY (STORE_NO) REFERENCES BBN_STORE (STORE_NO)
);

CREATE SEQUENCE SEQ_STOREWINE_NO;

COMMENT ON COLUMN STORE_WINES.NO IS '와인번호';
COMMENT ON COLUMN STORE_WINES.STORE_NO IS '한글명';
COMMENT ON COLUMN STORE_WINES.WINE_ENG IS '영어명';
COMMENT ON COLUMN STORE_WINES.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN STORE_WINES.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN STORE_WINES.STORE_NO IS '상점고유번호';

---------------------------------------------------------------------------
-------------- WAGLE_BOARD 관련 테이블 ------------
------------------------------------------------

CREATE TABLE WAGLE_BOARD (
    WAGLE_NO NUMBER,
    WRITER_NO NUMBER,
    WINE_NO NUMBER,
    SHOP_NO NUMBER,
	WAGLE_TITLE VARCHAR2(50), 
	WAGLE_CONTENT VARCHAR2(2000), 
	ORIGINAL_FILENAME VARCHAR2(100),
	RENAMED_FILENAME VARCHAR2(100), 
	READCOUNT NUMBER DEFAULT 0,
    SCRAPCOUNT NUMBER DEFAULT 0,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATE DEFAULT SYSDATE, 
    MODIFY_DATE DATE DEFAULT SYSDATE,
    CATEGORY VARCHAR2(20),
    CONSTRAINT PK_BOARD_NO PRIMARY KEY(WAGLE_NO),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO) ON DELETE SET NULL
);

    --CONSTRAINT FK_WINE_NO FOREIGN KEY(WINE_NO) REFERENCES BEBENO_WINEBOARD(WINE_BNO) ON DELETE SET NULL,
    --CONSTRAINT FK_SHOP_NO FOREIGN KEY(SHOP_NO) REFERENCES BBN_STORE(STORE_NO) ON DELETE SET NULL

CREATE SEQUENCE SEQ_WAGLE_BOARD_NO;

COMMENT ON COLUMN WAGLE_BOARD.WAGLE_NO IS '게시글번호';
COMMENT ON COLUMN WAGLE_BOARD.WRITER_NO IS '게시글작성자';
COMMENT ON COLUMN WAGLE_BOARD.WINE_NO IS '참조와인번호';
COMMENT ON COLUMN WAGLE_BOARD.SHOP_NO IS '참조가게번호';
COMMENT ON COLUMN WAGLE_BOARD.WAGLE_TITLE IS '게시글제목';
COMMENT ON COLUMN WAGLE_BOARD.WAGLE_CONTENT IS '게시글내용';
COMMENT ON COLUMN WAGLE_BOARD.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN WAGLE_BOARD.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN WAGLE_BOARD.READCOUNT IS '조회수';
COMMENT ON COLUMN WAGLE_BOARD.SCRAPCOUNT IS '스크랩수';
COMMENT ON COLUMN WAGLE_BOARD.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN WAGLE_BOARD.CREATE_DATE IS '게시글올린날짜';
COMMENT ON COLUMN WAGLE_BOARD.MODIFY_DATE IS '게시글수정날짜';
COMMENT ON COLUMN WAGLE_BOARD.CATEGORY IS '와글타입';

INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '게시글 1',  '와인후기', '원본파일명.txt', 'wagle1.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '게시글 2',  '와인후기', '원본파일명.txt', 'wagle2.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '게시글 3',  '와인후기', '원본파일명.txt', 'wagle3.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '게시글 4',  '와인후기', '원본파일명.txt', 'wagle4.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '타이틀 5',  '와인후기', '원본파일명.txt', 'wagle5.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '타이틀 6',  '와인후기', '원본파일명.txt', 'wagle6.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '타이틀 7',  '와인후기', '원본파일명.txt', 'wagle7.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '타이틀 8',  '와인후기', '원본파일명.txt', 'wagle8.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '타이틀 9',  '와인후기', '원본파일명.txt', 'wagle9.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '타이틀 10',  '와인후기', '원본파일명.txt', 'wagle10.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');
INSERT INTO WAGLE_BOARD VALUES(SEQ_WAGLE_BOARD_NO.NEXTVAL, 1, '', '', '타이틀 11',  '와인후기', '원본파일명.txt', 'wagle11.png', DEFAULT, DEFAULT, 'Y', SYSDATE, SYSDATE, 'wine');

-- 총 게시글 갯수
-- SELECT COUNT(*) FROM BOARD WHERE STATUS='Y'

-- 조회수 증가
-- UPDATE BOARD SET READCOUNT=? WHERE NO=?

-- 게시글 작성
-- INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,?,?,?,?,?,DEFAULT,DEFAULT,DEFAULT,DEFAULT)

-- 게시글 수정
-- UPDATE BOARD SET TITLE=?,CONTENT=?,ORIGINAL_FILENAME=?,RENAMED_FILENAME=?,MODIFY_DATE=SYSDATE WHERE NO=?

-- 게시글 삭제
-- UPDATE BOARD SET STATUS=? WHERE NO=?

------------------------------------------------
---------- WAGLE_BOARD_REPLY 관련 테이블 --------
------------------------------------------------

CREATE TABLE WAGLE_BOARD_REPLY(
      NO NUMBER PRIMARY KEY,
      W_NO NUMBER,
      WRITER_NO NUMBER,
      CONTENT VARCHAR2(400),
      STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
      CREATE_DATE DATE DEFAULT SYSDATE,
      MODIFY_DATE DATE DEFAULT SYSDATE,
      FOREIGN KEY (W_NO) REFERENCES WAGLE_BOARD (WAGLE_NO),
      FOREIGN KEY (WRITER_NO) REFERENCES MEMBER
);

CREATE SEQUENCE SEQ_WAGLE_REPLY_NO;

COMMENT ON COLUMN WAGLE_BOARD_REPLY.NO IS '댓글번호';
COMMENT ON COLUMN WAGLE_BOARD_REPLY.W_NO IS '댓글이작성된게시글';
COMMENT ON COLUMN WAGLE_BOARD_REPLY.WRITER_NO IS '댓글작성자';
COMMENT ON COLUMN WAGLE_BOARD_REPLY.CONTENT IS '댓글내용';
COMMENT ON COLUMN WAGLE_BOARD_REPLY.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN WAGLE_BOARD_REPLY.CREATE_DATE IS '댓글올린날짜';
COMMENT ON COLUMN WAGLE_BOARD_REPLY.MODIFY_DATE IS '댓글수정날짜';

INSERT INTO WAGLE_BOARD_REPLY VALUES(SEQ_WAGLE_REPLY_NO.NEXTVAL, 1, 1, '안녕하세요.', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO WAGLE_BOARD_REPLY VALUES(SEQ_WAGLE_REPLY_NO.NEXTVAL, 1, 1, '반갑습니다.', DEFAULT, DEFAULT, DEFAULT);

------------------------------------------------
-------------- WAGLE_FILE 관련 테이블 ------------
------------------------------------------------
CREATE TABLE WAGLE_FILE (
    W_FILE_NO NUMBER PRIMARY KEY,
    W_NO NUMBER,
    ORIGINAL_FILENAME VARCHAR2(100),
	RENAMED_FILENAME VARCHAR2(100),
    FOREIGN KEY (W_NO) REFERENCES WAGLE_BOARD (WAGLE_NO)
);

CREATE SEQUENCE SEQ_W_FILE_NO;

COMMENT ON COLUMN WAGLE_FILE.W_FILE_NO IS '파일고유번호';
COMMENT ON COLUMN WAGLE_FILE.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN WAGLE_FILE.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN WAGLE_FILE.W_NO IS '와글고유번호';

COMMIT;                                      
